import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { GlobalContext } from "@/contexts/GlobalContext";
import { useState } from "react";
import ContextWrapper from "@/components/ContextWrapper";
import { useRouter } from "next/navigation";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Anaqa Maghribiya - CRM",
  description: "Generated by create next app",
  viewport:{width:'device-width', initialScale:1}
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  
  return (
    <html lang="en"  style={{maxHeight:'var(--portview-height)'}}>
      <body className={inter.className}>
        <ContextWrapper >
          {children}
        </ContextWrapper>
        </body>
    </html>
  );
}
