const StatusStyling={
    "🕐 Reporté One":"#76a5af",
    "⛔ Annulé One":"#ea9999",
    "Confirmed":"#00b11f",
    "Pas de réponse+Sms":"#e69138",
    "En Att Change address":"#c3ad00",
    "🕐 Reporté":"#00ffff",
    "Expedié":"#0000ff",
    "Pas de réponse":"#6aa84f",
    "Changement d adresse":"#f9cb9c",
    "Injoignable":"#ff00ff",
    "Ramassé":"#b7b7b7",
    "Casa Sheets":"#b4a7d6",
    "✅ Livré":"#00b11f",
    "Processing":"#ff9900",
    "♻ Change Livré":"#00b11f",
    "⛔ Retouré - Refusé":"#ff0000",
    "⛔ Retouré - Annulé":"#ff0000",
    "Ville Indisponible":"#af6660",
    "In Site":"#b7e1cd",
    "Confirmed Et Reporté One":"#cbdf51",
    "Mise en distribution":"#25a0d7",
    "En Cours de Livraison":"#1dd0e7",
    "Rembourssement":"#e484e0",
    "Out Stock":"#ea4335",
    "Hors Zone":"Hors Zone",
    "Confi - Client intéressé":"#4dd0e1",
    "Demande de Change":"#45818e",
    
    }
    export default StatusStyling;